/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IButton;
import com.bh.at.iuiutils.IText;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CMobilePage;
import com.bh.icommonbaseutils.IJSONO;

public class HazardAlertPage extends CMobilePage {
  private static final IJSONO titleConfig = cbf.getJSONOFromString("{\"loc\":[\"id\",\"android:id/alertTitle\"],\"name\":\"title\"}");

  private static final IJSONO messageConfig = cbf.getJSONOFromString("{\"loc\":[\"id\",\"android:id/message\"],\"name\":\"message\"}");

  private static final IJSONO okConfig = cbf.getJSONOFromString("{\"loc\":[\"id\",\"com.bently.scout200:id/warningconfirm\"],\"name\":\"ok\"}");

  public IText title;

  public IText message;

  public IButton ok;

  public HazardAlertPage(IJSONO uiDriverCaps) {
    super(uiDriverCaps);
  }

  @Override
  public void quit() {
    super.quit();
  }

  @Override
  public HazardAlertPage init(int... optTimeoutInSecs) {
    super.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public HazardAlertPage initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    title.init(optTimeoutInSecs);
    message.init(optTimeoutInSecs);
    ok.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public HazardAlertPage collectData() {
    super.collectData();
    title.collectData();
    message.collectData();
    ok.collectData();

    return this;
  }

  @Override
  protected HazardAlertPage createComponents() {
    super.createComponents();
    title = uif.getText(UiHelper.config.createConfig(titleConfig, this));
    message = uif.getText(UiHelper.config.createConfig(messageConfig, this));
    ok = uif.getButton(UiHelper.config.createConfig(okConfig, this));

    return this;
  }
}
