/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IImg;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CMobilePage;
import com.bh.icommonbaseutils.IJSONO;

public class SplashPage extends CMobilePage {
  private static final IJSONO splashImgConfig = cbf.getJSONOFromString("{\"loc\":[\"id\",\"android:id/content\"],\"name\":\"splashImg\"}");

  public IImg splashImg;

  public SplashPage(IJSONO uiDriverCaps) {
    super(uiDriverCaps);
  }

  @Override
  public void quit() {
    super.quit();
  }

  @Override
  public SplashPage init(int... optTimeoutInSecs) {
    super.init(optTimeoutInSecs);

    return this;
  }

  @Override
  protected SplashPage createComponents() {
    super.createComponents();
    splashImg = uif.getImg(UiHelper.config.createConfig(splashImgConfig, this));

    return this;
  }
}
