/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IConfig;
import com.bh.at.iuiutils.IText;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.icommonbaseutils.IJSONO;

public class CAddEditParamsetPage extends CElement {
  private static final IJSONO typeConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='paramsetconfig_type_navbar']\",\"webview\"],\"name\":\"type\"}");

  private static final IJSONO storeUnitConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='paramsetconfig_storeunit_navbar']\"],\"name\":\"storeUnit\"}");

  private static final IJSONO cancelConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorssetup_cancel_button']\"],\"name\":\"cancel\"}");

  private static final IJSONO saveConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorssetup_save_button']\"],\"name\":\"save\"}");

  private static final IJSONO deleteConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorssetup_delete_button']\"],\"name\":\"delete\"}");

  public IText type;

  public IText storeUnit;

  public IText cancel;

  public IText save;

  public IText delete;

  public CAddEditParamsetPage(IConfig config) {
    super(config);
  }

  @Override
  public CAddEditParamsetPage initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    type.init(optTimeoutInSecs);
    storeUnit.init(optTimeoutInSecs);
    save.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public CAddEditParamsetPage collectData() {
    if (elementExists()) {
      super.collectData();
      type.collectData();
      storeUnit.collectData();
      save.collectData();
    }

    return this;
  }

  @Override
  protected CAddEditParamsetPage createComponents() {
    super.createComponents();
    type = uif.getText(UiHelper.config.createConfig(typeConfig, this));
    storeUnit = uif.getText(UiHelper.config.createConfig(storeUnitConfig, this));
    cancel = uif.getText(UiHelper.config.createConfig(cancelConfig, this));
    save = uif.getText(UiHelper.config.createConfig(saveConfig, this));
    delete = uif.getText(UiHelper.config.createConfig(deleteConfig, this));

    return this;
  }
}
