/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IConfig;
import com.bh.at.iuiutils.IText;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.icommonbaseutils.IJSONO;

public class CAddEditSensorPage extends CElement {
  private static final IJSONO nameConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_name_rightcontent']\",\"webview\"],\"name\":\"name\"}");

  private static final IJSONO typeConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_type_rightcontent']\"],\"name\":\"type\"}");

  private static final IJSONO volRangeCouplingConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_channelinput_rightcontent']\"],\"name\":\"volRangeCoupling\"}");

  private static final IJSONO settlingTimeConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_settlingtime_rightcontent']\"],\"name\":\"settlingTime\"}");

  private static final IJSONO autoSettlingConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_autosettling_rightcontent']\"],\"name\":\"autoSettling\"}");

  private static final IJSONO sensitivityConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_sensitivity_rightcontent']\"],\"name\":\"sensitivity\"}");

  private static final IJSONO unitConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_unit_rightcontent']\"],\"name\":\"unit\"}");

  private static final IJSONO driveCurrentConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_drivecurrent_rightcontent']\"],\"name\":\"driveCurrent\"}");

  private static final IJSONO biasVolCheckConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_biasvoltage_rightcontent']\"],\"name\":\"biasVolCheck\"}");

  private static final IJSONO zeroDCOffsetConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorsetup_dcoffset_rightcontent']\"],\"name\":\"zeroDCOffset\"}");

  private static final IJSONO cancelConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorssetup_cancel_button']\"],\"name\":\"cancel\"}");

  private static final IJSONO saveConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorssetup_save_button']\"],\"name\":\"save\"}");

  private static final IJSONO deleteConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensorssetup_delete_button']\"],\"name\":\"delete\"}");

  public IText name;

  public IText type;

  public IText volRangeCoupling;

  public IText settlingTime;

  public IText autoSettling;

  public IText sensitivity;

  public IText unit;

  public IText driveCurrent;

  public IText biasVolCheck;

  public IText zeroDCOffset;

  public IText cancel;

  public IText save;

  public IText delete;

  public CAddEditSensorPage(IConfig config) {
    super(config);
  }

  @Override
  public CAddEditSensorPage initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    name.init(optTimeoutInSecs);
    type.init(optTimeoutInSecs);
    volRangeCoupling.init(optTimeoutInSecs);
    settlingTime.init(optTimeoutInSecs);
    autoSettling.init(optTimeoutInSecs);
    sensitivity.init(optTimeoutInSecs);
    unit.init(optTimeoutInSecs);
    driveCurrent.init(optTimeoutInSecs);
    save.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public CAddEditSensorPage collectData() {
    if (elementExists()) {
      super.collectData();
      name.collectData();
      type.collectData();
      volRangeCoupling.collectData();
      settlingTime.collectData();
      autoSettling.collectData();
      sensitivity.collectData();
      unit.collectData();
      driveCurrent.collectData();
      save.collectData();
    }

    return this;
  }

  @Override
  protected CAddEditSensorPage createComponents() {
    super.createComponents();
    name = uif.getText(UiHelper.config.createConfig(nameConfig, this));
    type = uif.getText(UiHelper.config.createConfig(typeConfig, this));
    volRangeCoupling = uif.getText(UiHelper.config.createConfig(volRangeCouplingConfig, this));
    settlingTime = uif.getText(UiHelper.config.createConfig(settlingTimeConfig, this));
    autoSettling = uif.getText(UiHelper.config.createConfig(autoSettlingConfig, this));
    sensitivity = uif.getText(UiHelper.config.createConfig(sensitivityConfig, this));
    unit = uif.getText(UiHelper.config.createConfig(unitConfig, this));
    driveCurrent = uif.getText(UiHelper.config.createConfig(driveCurrentConfig, this));
    biasVolCheck = uif.getText(UiHelper.config.createConfig(biasVolCheckConfig, this));
    zeroDCOffset = uif.getText(UiHelper.config.createConfig(zeroDCOffsetConfig, this));
    cancel = uif.getText(UiHelper.config.createConfig(cancelConfig, this));
    save = uif.getText(UiHelper.config.createConfig(saveConfig, this));
    delete = uif.getText(UiHelper.config.createConfig(deleteConfig, this));

    return this;
  }
}
