/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IButton;
import com.bh.at.iuiutils.ICheckbox;
import com.bh.at.iuiutils.IConfig;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.icommonbaseutils.IJSONO;

public class CDevicesPage extends CElement {
  private static final IJSONO simulatorCBoxConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='devices_Simulator_checkbox']\",\"webview\"],\"name\":\"simulatorCBox\"}");

  private static final IJSONO doneConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='devices_done_button']\"],\"name\":\"done\"}");

  public ICheckbox simulatorCBox;

  public IButton done;

  public CDevicesPage(IConfig config) {
    super(config);
  }

  @Override
  public CDevicesPage initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    simulatorCBox.init(optTimeoutInSecs);
    done.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public CDevicesPage collectData() {
    if (elementExists()) {
      super.collectData();
      simulatorCBox.collectData();
      done.collectData();
    }

    return this;
  }

  @Override
  protected CDevicesPage createComponents() {
    super.createComponents();
    simulatorCBox = uif.getCheckbox(UiHelper.config.createConfig(simulatorCBoxConfig, this));
    done = uif.getButton(UiHelper.config.createConfig(doneConfig, this));

    return this;
  }
}
