/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IButton;
import com.bh.at.iuiutils.IConfig;
import com.bh.at.iuiutils.IText;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.icommonbaseutils.IJSONO;

public class CDialogPage extends CElement {
  private static final IJSONO okButtonConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='message_ok']\",\"webview\"],\"name\":\"okButton\"}");

  private static final IJSONO dialogTextConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='message_text_info']\"],\"name\":\"dialogText\"}");

  private static final IJSONO fileOkConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='file_done_button']\"],\"name\":\"fileOk\"}");

  private static final IJSONO fileCancelConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='file_cancel_button']\"],\"name\":\"fileCancel\"}");

  private static final IJSONO FileLoadSuccessConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='Load File Success_modal']\"],\"name\":\"FileLoadSuccess\"}");

  public IButton okButton;

  public IText dialogText;

  public IText fileOk;

  public IText fileCancel;

  public IText FileLoadSuccess;

  public CDialogPage(IConfig config) {
    super(config);
  }

  @Override
  public CDialogPage initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    //okButton.init(optTimeoutInSecs);
    //dialogText.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public CDialogPage collectData() {
    if (elementExists()) {
      super.collectData();
      //okButton.collectData();
      //dialogText.collectData();
    }

    return this;
  }

  @Override
  protected CDialogPage createComponents() {
    super.createComponents();
    okButton = uif.getButton(UiHelper.config.createConfig(okButtonConfig, this));
    dialogText = uif.getText(UiHelper.config.createConfig(dialogTextConfig, this));
    fileOk = uif.getText(UiHelper.config.createConfig(fileOkConfig, this));
    fileCancel = uif.getText(UiHelper.config.createConfig(fileCancelConfig, this));
    FileLoadSuccess = uif.getText(UiHelper.config.createConfig(FileLoadSuccessConfig, this));

    return this;
  }
}
