/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IConfig;
import com.bh.at.iuiutils.IText;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.icommonbaseutils.IJSONO;

public class CdriveCurrentSensor extends CElement {
  private static final IJSONO onConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensordrivecurrent_On_listitem']\",\"webview\"],\"name\":\"on\"}");

  private static final IJSONO offConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='sensordrivecurrent_Off_listitem']\"],\"name\":\"off\"}");

  public IText on;

  public IText off;

  public CdriveCurrentSensor(IConfig config) {
    super(config);
  }

  @Override
  public CdriveCurrentSensor initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    on.init(optTimeoutInSecs);
    off.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public CdriveCurrentSensor collectData() {
    if (elementExists()) {
      super.collectData();
      on.collectData();
      off.collectData();
    }

    return this;
  }

  @Override
  protected CdriveCurrentSensor createComponents() {
    super.createComponents();
    on = uif.getText(UiHelper.config.createConfig(onConfig, this));
    off = uif.getText(UiHelper.config.createConfig(offConfig, this));

    return this;
  }
}
