/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IConfig;
import com.bh.at.iuiutils.IImg;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.at.uiutils.CElements;
import com.bh.at.uiutils.CImg;
import com.bh.icommonbaseutils.IJSONO;

public class CPoints extends CElement {
  private static final IJSONO pointsCompConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[contains(@class,'app-ui-schedule-')]\"],\"name\":\"points\"}");

  private static final IJSONO pointsInCompConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[contains(@class,'app-ui-schedule-')]\"],\"name\":\"points\"}");

  //private static final IJSONO pointsConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[contains(@class,'app-ui-schedule-')]\"],\"name\":\"points\"}");

  public CElements<IImg> pointsComp;
  public CElements<IImg> pointsInComp;

  public CPoints(IConfig config) {
    super(config);
  }

  @Override
  protected CPoints createComponents() {
    super.createComponents();
    pointsComp = new CElements<>(CImg::new, UiHelper.config.createConfig(pointsCompConfig, this));
    pointsInComp = new CElements<>(CImg::new, UiHelper.config.createConfig(pointsInCompConfig, this));

    return this;
  }
}
