/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IConfig;
import com.bh.at.iuiutils.IText;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.at.uiutils.CElements;
import com.bh.at.uiutils.CText;
import com.bh.icommonbaseutils.IJSONO;

public class CRFolderPage extends CElement {
  private static final IJSONO selectFolderConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[starts-with(@test-tag,'folder_') and contains(@test-tag,'_listitem')]\",\"webview\"],\"name\":\"selectFolder\"}");


  public CElements<IText> selectFolder;

  public CRFolderPage(IConfig config) {
    super(config);
  }

  @Override
  protected CRFolderPage createComponents() {
    super.createComponents();
    //selectFolder = uif.getText(UiHelper.config.createConfig(selectFolderConfig, this));
    selectFolder = new CElements<>(CText::new, UiHelper.config.createConfig(selectFolderConfig, this));

    return this;
  }
}
