/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.IConfig;
import com.bh.at.iuiutils.IText;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.at.uiutils.CElements;
import com.bh.at.uiutils.CText;
import com.bh.icommonbaseutils.IJSONO;

public class CRoutePage extends CElement {
  private static final IJSONO selectEnterpriseConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='routes_enterprise_navbar']\",\"webview\"],\"name\":\"selectEnterprise\"}");

  private static final IJSONO selectFolderConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='routes_folder_navbar']\",\"webview\"],\"name\":\"selectFolder\"}");

  private static final IJSONO selectRouteConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[starts-with(@test-tag,'routes_') and contains(@test-tag,'_rightcontent')]\",\"webview\"],\"name\":\"selectRoute\"}");

  public IText selectEnterprise;

  public IText selectFolder;

  public CElements<IText> selectRoute;

  public CRoutePage(IConfig config) {
    super(config);
  }

  @Override
  public CRoutePage initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    selectEnterprise.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public CRoutePage collectData() {
    if (elementExists()) {
      super.collectData();
      selectEnterprise.collectData();
    }

    return this;
  }

  @Override
  protected CRoutePage createComponents() {
    super.createComponents();
    selectEnterprise = uif.getText(UiHelper.config.createConfig(selectEnterpriseConfig, this));
    selectFolder = uif.getText(UiHelper.config.createConfig(selectFolderConfig, this));
   // selectRoute = uif.getText(UiHelper.config.createConfig(selectRouteConfig, this));
    selectRoute = new CElements<>(CText::new, UiHelper.config.createConfig(selectRouteConfig, this));


    return this;
  }
}
