/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.ICheckbox;
import com.bh.at.iuiutils.IConfig;
import com.bh.at.iuiutils.IText;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.icommonbaseutils.IJSONO;

public class CSensorSetupPage extends CElement {
  private static final IJSONO ch1BoxConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='channellist_Ch1_checkbox']\",\"webview\"],\"name\":\"ch1Box\"}");

  private static final IJSONO ch2BoxConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='channellist_Ch2_checkbox']\"],\"name\":\"ch2Box\"}");

  private static final IJSONO ch3BoxConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='channellist_Ch3_checkbox']\"],\"name\":\"ch3Box\"}");

  private static final IJSONO ch4BoxConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='channellist_Ch4_checkbox']\"],\"name\":\"ch4Box\"}");

  private static final IJSONO ch1NameConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='channellist_Ch1_rightcontent']\"],\"name\":\"ch1Name\"}");

  private static final IJSONO ch2NameConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='channellist_Ch2_rightcontent']\"],\"name\":\"ch2Name\"}");

  private static final IJSONO ch3NameConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='channellist_Ch3_rightcontent']\"],\"name\":\"ch3Name\"}");

  private static final IJSONO ch4NameConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='channellist_Ch4_rightcontent']\"],\"name\":\"ch4Name\"}");

  private static final IJSONO doneConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='message_done_button']\"],\"name\":\"done\"}");

  public ICheckbox ch1Box;

  public ICheckbox ch2Box;

  public ICheckbox ch3Box;

  public ICheckbox ch4Box;

  public IText ch1Name;

  public IText ch2Name;

  public IText ch3Name;

  public IText ch4Name;

  public IText done;

  public CSensorSetupPage(IConfig config) {
    super(config);
  }

  @Override
  public CSensorSetupPage initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    ch1Box.init(optTimeoutInSecs);
    ch2Box.init(optTimeoutInSecs);
    ch3Box.init(optTimeoutInSecs);
    ch4Box.init(optTimeoutInSecs);
    ch1Name.init(optTimeoutInSecs);
    ch2Name.init(optTimeoutInSecs);
    ch3Name.init(optTimeoutInSecs);
    ch4Name.init(optTimeoutInSecs);
    done.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public CSensorSetupPage collectData() {
    if (elementExists()) {
      super.collectData();
      ch1Box.collectData();
      ch2Box.collectData();
      ch3Box.collectData();
      ch4Box.collectData();
      ch1Name.collectData();
      ch2Name.collectData();
      ch3Name.collectData();
      ch4Name.collectData();
      done.collectData();
    }

    return this;
  }

  @Override
  protected CSensorSetupPage createComponents() {
    super.createComponents();
    ch1Box = uif.getCheckbox(UiHelper.config.createConfig(ch1BoxConfig, this));
    ch2Box = uif.getCheckbox(UiHelper.config.createConfig(ch2BoxConfig, this));
    ch3Box = uif.getCheckbox(UiHelper.config.createConfig(ch3BoxConfig, this));
    ch4Box = uif.getCheckbox(UiHelper.config.createConfig(ch4BoxConfig, this));
    ch1Name = uif.getText(UiHelper.config.createConfig(ch1NameConfig, this));
    ch2Name = uif.getText(UiHelper.config.createConfig(ch2NameConfig, this));
    ch3Name = uif.getText(UiHelper.config.createConfig(ch3NameConfig, this));
    ch4Name = uif.getText(UiHelper.config.createConfig(ch4NameConfig, this));
    done = uif.getText(UiHelper.config.createConfig(doneConfig, this));

    return this;
  }
}
