/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.page.component;

import static com.bh.at.uiutils.UIUtilsFactory.uif;
import static com.bh.commonbaseutils.CommonBaseFactory.cbf;

import com.bh.at.iuiutils.ICheckbox;
import com.bh.at.iuiutils.IConfig;
import com.bh.at.s1scout200.tester.UiHelper;
import com.bh.at.uiutils.CElement;
import com.bh.icommonbaseutils.IJSONO;

public class CSimulatorPage extends CElement {
  private static final IJSONO dataCollectorSimulatorCBoxConfig = cbf.getJSONOFromString("{\"loc\":[\"xpath\",\"//*[@test-tag='datacollectorsimulator_enable_checkbox']\",\"webview\"],\"name\":\"dataCollectorSimulatorCBox\"}");

  public ICheckbox dataCollectorSimulatorCBox;

  public CSimulatorPage(IConfig config) {
    super(config);
  }

  @Override
  public CSimulatorPage initComponents(int... optTimeoutInSecs) {
    super.initComponents(optTimeoutInSecs);
    dataCollectorSimulatorCBox.init(optTimeoutInSecs);

    return this;
  }

  @Override
  public CSimulatorPage collectData() {
    if (elementExists()) {
      super.collectData();
      dataCollectorSimulatorCBox.collectData();
    }

    return this;
  }

  @Override
  protected CSimulatorPage createComponents() {
    super.createComponents();
    dataCollectorSimulatorCBox = uif.getCheckbox(UiHelper.config.createConfig(dataCollectorSimulatorCBoxConfig, this));

    return this;
  }
}
