/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.tester;

import java.util.List;

public final class SensorConfigTester extends BaseTester {
  public void f10(String p0) {
    System.out.println(">>>>> sensorConfig: Function f10 (Select any channel to setup the sensor configuration CH1) not fully implemented");
  }

  public void f14(String p0) {
    System.out.println(">>>>> sensorConfig: Function f14 (Change the Voltage Range and Coupling to be of DC Coupling type) not fully implemented");
  }

  public void f15() {
    System.out.println(">>>>> sensorConfig: Function f15 (Modify the Zero DC Offset property) not fully implemented");
  }

  public void f16(List<String> list) {
    System.out.println(">>>>> sensorConfig: Function f16 (Change the sensor type to each of the available sensor settings) not fully implemented");
  }

  public void f18() {
    System.out.println(">>>>> sensorConfig: Function f18 (Modify the Units property) not fully implemented");
  }

  public void f19() {
    System.out.println(">>>>> sensorConfig: Function f19 (Modify the Settling Time property) not fully implemented");
  }

  public void f20() {
    System.out.println(">>>>> sensorConfig: Function f20 (Modify the Auto Settling property) not fully implemented");
  }

  public void f21() {
    System.out.println(">>>>> sensorConfig: Function f21 (Modify the Sensitivity property) not fully implemented");
  }

  public void f22() {
    System.out.println(">>>>> sensorConfig: Function f22 (Modify the Drive Current property) not fully implemented");
  }

  public void f24() {
    System.out.println(">>>>> sensorConfig: Function f24 (Navigate back to the channel selection screen) not fully implemented");
  }

  public void f25() {
    System.out.println(">>>>> sensorConfig: Function f25 (Navigates back) not fully implemented");
  }

  public void f27(String p0) {
    System.out.println(">>>>> sensorConfig: Function f27 (Edit the previously configured sensor DemoSensor) not fully implemented");
  }

  public void f28() {
    System.out.println(">>>>> sensorConfig: Function f28 (Modify all properties of the sensor to some other value within limits) not fully implemented");
  }

  public void f32() {
    System.out.println(">>>>> sensorConfig: Function f32 (Delete the sensor) not fully implemented");
  }
}
