/****************************************************************************************************************
 * BH Confidential                                                                                              *
 * Unpublished Copyright 2021.  Baker Hughes Company                                                            *
 *                                                                                                              *
 * NOTICE:  All information contained herein is, and remains the property of  Baker Hughes Company,  and/or its *
 * affiliates. The intellectual and technical concepts contained herein are proprietary to Baker Hughes Company *
 * and/or its affiliates and may be covered by  patents,  copyrights,  and/or trade secrets.   Dissemination of *
 * this information or reproduction of this material is  strictly forbidden unless prior  written permission is *
 * obtained from Baker Hughes Company.                                                                          *
 ***************************************************************************************************************/

   /* ** AUTOGENERATED - DO NOT MODIFY, ANY MODIFICATIONS WILL BE OVERWRITTEN!!!!! ** */

package com.bh.at.s1scout200.tester;

public final class VerifyPlotsTester extends BaseTester {
  public void f42() {

    System.out.println(">>>>> verifyPlots: Function f42 (user navigates Settings Measuring Units) not fully implemented");
  }

  public void f43(String p0, String p1) {
    System.out.println(">>>>> verifyPlots: Function f43 (user selects <units> in Unit Set) not fully implemented");
  }

  public void f46(String p0) {
    System.out.println(">>>>> verifyPlots: Function f46 (a new Parameter set with Store Unit <parameterSet>) not fully implemented");
  }

  public void f50(String p0) {
    System.out.println(">>>>> verifyPlots: Function f50 (Change the sensor type to <parameterSet>) not fully implemented");
  }

  public void f52() {
    System.out.println(">>>>> verifyPlots: Function f52 (navigates back) not fully implemented");
  }

  public void f53() {
    System.out.println(">>>>> verifyPlots: Function f53 (user clicks on Measure on Measure Configuration Screen) not fully implemented");
  }

  public void f54() {
    System.out.println(">>>>> verifyPlots: Function f54 (user pauses the measurement) not fully implemented");
  }

  public void f55(String p0, String p1) {
    System.out.println(">>>>> verifyPlots: Function f55 (user verifies measure units <spectrumUnit> and <WaveformUnit>) not fully implemented");
  }
}
